// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.3
// source: divera-alarm.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Alarm struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ForeignId string           `protobuf:"bytes,2,opt,name=foreign_id,json=foreignId,proto3" json:"foreign_id,omitempty"`
	Title     string           `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Text      string           `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	Address   string           `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Position  *Alarm_LatLng    `protobuf:"bytes,6,opt,name=position,proto3" json:"position,omitempty"`
	Priority  bool             `protobuf:"varint,7,opt,name=priority,proto3" json:"priority,omitempty"`
	Created   *Alarm_Timestamp `protobuf:"bytes,8,opt,name=created,proto3" json:"created,omitempty"`
	Updated   *Alarm_Timestamp `protobuf:"bytes,9,opt,name=updated,proto3" json:"updated,omitempty"`
}

func (x *Alarm) Reset() {
	*x = Alarm{}
	if protoimpl.UnsafeEnabled {
		mi := &file_divera_alarm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alarm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alarm) ProtoMessage() {}

func (x *Alarm) ProtoReflect() protoreflect.Message {
	mi := &file_divera_alarm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alarm.ProtoReflect.Descriptor instead.
func (*Alarm) Descriptor() ([]byte, []int) {
	return file_divera_alarm_proto_rawDescGZIP(), []int{0}
}

func (x *Alarm) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Alarm) GetForeignId() string {
	if x != nil {
		return x.ForeignId
	}
	return ""
}

func (x *Alarm) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Alarm) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Alarm) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Alarm) GetPosition() *Alarm_LatLng {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *Alarm) GetPriority() bool {
	if x != nil {
		return x.Priority
	}
	return false
}

func (x *Alarm) GetCreated() *Alarm_Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Alarm) GetUpdated() *Alarm_Timestamp {
	if x != nil {
		return x.Updated
	}
	return nil
}

type Alarm_Timestamp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Represents seconds of UTC time since Unix epoch
	// 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
	// 9999-12-31T23:59:59Z inclusive.
	Seconds int64 `protobuf:"varint,1,opt,name=seconds,proto3" json:"seconds,omitempty"`
}

func (x *Alarm_Timestamp) Reset() {
	*x = Alarm_Timestamp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_divera_alarm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alarm_Timestamp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alarm_Timestamp) ProtoMessage() {}

func (x *Alarm_Timestamp) ProtoReflect() protoreflect.Message {
	mi := &file_divera_alarm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alarm_Timestamp.ProtoReflect.Descriptor instead.
func (*Alarm_Timestamp) Descriptor() ([]byte, []int) {
	return file_divera_alarm_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Alarm_Timestamp) GetSeconds() int64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

type Alarm_LatLng struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Latitude  float64 `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude float64 `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
}

func (x *Alarm_LatLng) Reset() {
	*x = Alarm_LatLng{}
	if protoimpl.UnsafeEnabled {
		mi := &file_divera_alarm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alarm_LatLng) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alarm_LatLng) ProtoMessage() {}

func (x *Alarm_LatLng) ProtoReflect() protoreflect.Message {
	mi := &file_divera_alarm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alarm_LatLng.ProtoReflect.Descriptor instead.
func (*Alarm_LatLng) Descriptor() ([]byte, []int) {
	return file_divera_alarm_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Alarm_LatLng) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Alarm_LatLng) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_divera_alarm_proto protoreflect.FileDescriptor

var file_divera_alarm_proto_rawDesc = []byte{
	0x0a, 0x12, 0x64, 0x69, 0x76, 0x65, 0x72, 0x61, 0x2d, 0x61, 0x6c, 0x61, 0x72, 0x6d, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x84, 0x03, 0x0a, 0x05, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x66, 0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x66, 0x6f, 0x72, 0x65, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x29, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x2e, 0x4c, 0x61, 0x74, 0x4c,
	0x6e, 0x67, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08,
	0x70, 0x72, 0x69, 0x6f, 0x72, 0x69, 0x74, 0x79, 0x12, 0x2a, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x41, 0x6c, 0x61, 0x72,
	0x6d, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x41, 0x6c, 0x61, 0x72, 0x6d, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x1a, 0x25, 0x0a, 0x09, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x1a, 0x42, 0x0a, 0x06, 0x4c, 0x61, 0x74, 0x4c, 0x6e,
	0x67, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x01, 0x52, 0x08, 0x6c, 0x61, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x09, 0x6c, 0x6f, 0x6e, 0x67, 0x69, 0x74, 0x75, 0x64, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x43, 0x61, 0x70, 0x74, 0x61, 0x69,
	0x6e, 0x53, 0x74, 0x61, 0x6e, 0x64, 0x62, 0x79, 0x2f, 0x64, 0x69, 0x76, 0x65, 0x72, 0x61, 0x2d,
	0x6d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_divera_alarm_proto_rawDescOnce sync.Once
	file_divera_alarm_proto_rawDescData = file_divera_alarm_proto_rawDesc
)

func file_divera_alarm_proto_rawDescGZIP() []byte {
	file_divera_alarm_proto_rawDescOnce.Do(func() {
		file_divera_alarm_proto_rawDescData = protoimpl.X.CompressGZIP(file_divera_alarm_proto_rawDescData)
	})
	return file_divera_alarm_proto_rawDescData
}

var file_divera_alarm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_divera_alarm_proto_goTypes = []interface{}{
	(*Alarm)(nil),           // 0: Alarm
	(*Alarm_Timestamp)(nil), // 1: Alarm.Timestamp
	(*Alarm_LatLng)(nil),    // 2: Alarm.LatLng
}
var file_divera_alarm_proto_depIdxs = []int32{
	2, // 0: Alarm.position:type_name -> Alarm.LatLng
	1, // 1: Alarm.created:type_name -> Alarm.Timestamp
	1, // 2: Alarm.updated:type_name -> Alarm.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_divera_alarm_proto_init() }
func file_divera_alarm_proto_init() {
	if File_divera_alarm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_divera_alarm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alarm); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_divera_alarm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alarm_Timestamp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_divera_alarm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alarm_LatLng); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_divera_alarm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_divera_alarm_proto_goTypes,
		DependencyIndexes: file_divera_alarm_proto_depIdxs,
		MessageInfos:      file_divera_alarm_proto_msgTypes,
	}.Build()
	File_divera_alarm_proto = out.File
	file_divera_alarm_proto_rawDesc = nil
	file_divera_alarm_proto_goTypes = nil
	file_divera_alarm_proto_depIdxs = nil
}
